### PR TITLE
Darren authentication

### PR DESCRIPTION
**Pull request by darrenoday**
Fixed issue with registration, tested and working on my end

### CODE REVIEW

**Review by i-eva — DISMISSED** [review]
Two links appear on the homepage: register and log in. My test allows me to register a user. I can register a new user with a name and password. I can then log in under using the registered user name and password, and see my user name appear at the top of the page. The log in link changes to a log out link. When I check out the back end, I see that I change status from unauthorized to authorized, and back again when I log out.

**Comment by Suryavadana** [comment]
Registration , Login and Logout are Perfect!

**Review by Suryavadana — DISMISSED** [review]
Registration , Login and Logout are Perfect!

**Review by anumohan208 — APPROVED** [review]
Working fine.

**Pull request merged**
