### PR TITLE
Admin dashboard 

### PR DESCRIPTION
**Pull request by anumohan208**
Adding changes related to Admin dashboard functionality(View and Edit Events)

### CODE REVIEW

**Comment by Suryavadana** [comment]
Works good.

**Review by darrenoday — APPROVED** [review]
looks good

**Comment by i-eva** [comment]
We discussed the Admin Dashboard and plan to push this branch as is with more changes to come in a new branch. This branch runs for all of us!

**Review by i-eva — APPROVED** [review]
Branch tested and it runs!

**Review by Suryavadana — APPROVED** [review]
Works good

**Pull request merged**
